# Generated by Django 5.0.2 on 2024-04-01 12:21

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_channel_notify_at_views_post_stat_notified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="binding",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                to="api.usertelegrambinding",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="PostFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=api.models.get_filepath)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="api.post",
                    ),
                ),
            ],
        ),
    ]
