# Generated by Django 5.0.2 on 2024-04-01 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_channel_notify_at_views_post_stat_notified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmeasurement',
            old_name='value',
            new_name='views',
        ),
        migrations.AddField(
            model_name='postmeasurement',
            name='engagement_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
