# Generated by Django 5.0.2 on 2024-04-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_channel_binding_postfile'),
        ('api', '0004_rename_value_postmeasurement_views_channel_binding_and_more'),
    ]

    operations = [
    ]
