# Generated by Django 5.0.2 on 2024-04-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_merge_20240401_1616"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertelegrambinding",
            name="fetched_channels",
            field=models.JSONField(default=list),
        ),
    ]
