# Generated by Django 5.0.2 on 2024-04-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_usertelegrambinding_fetched_channels"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmeasurement",
            name="reactions",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
