# Generated by Django 5.0.2 on 2024-04-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_postmeasurement_reactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertelegrambinding",
            name="name",
            field=models.CharField(default="Account", max_length=255),
            preserve_default=False,
        ),
    ]
