# Generated by Django 5.0.2 on 2024-04-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_workflowstage_workflowpush_post_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="is_group",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
