# Generated by Django 5.0.2 on 2024-04-02 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_channel_is_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUploadedToTelegram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.IntegerField()),
                ("message_id", models.IntegerField()),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.usertelegrambinding",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.postfile",
                    ),
                ),
            ],
        ),
    ]
