# Generated by Django 5.0.2 on 2024-04-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_fileuploadedtotelegram_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="postfile",
            name="is_video_note",
            field=models.BooleanField(default=False),
        ),
    ]
